[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd ../.. && npm install"]

[phases.build]
cmds = ["cd ../.. && npm run build:shared && npm run build:api"]

[start]
cmd = "node dist/main.js"
